
''' An RNA string is a string formed from the alphabet containing 'A', 'C', 'G', and 'U'.

Given a DNA string t corresponding to a coding strand, its transcribed RNA string u is formed by replacing all occurrences of 'T' in t with 'U' in u.

Given: A DNA string t having length at most 1000 nt.

Return: The transcribed RNA string of t. '''

# Transcribing DNA string into RNA string:
def DNA2RNA(input_dna):  

    if not input_dna:
        return ''
    
    char = input_dna[0]
    if char == 'T':
        result_char = 'U'  
    else:
        result_char = char
    

    return result_char + DNA2RNA(input_dna[1:]) # concatenation of the current character and 
                                                # the result of recursively calling DNA2RNA on the rest of the DNA sequence.


data = 'GTGGGCTTAGTCAGGCTAATTGTAGGCTGCACGATCCATTGGCAGGAAGCTTCGGAAACCGGCTGCCTCGTATGAGCTTCCCAATGTAACCCACGAAAATCCTATATGTCAGCAGGTAGTAATCGGAGCTCATAGGGTCCCAAAGGGCGAGCACGGCTGCCGGAAACCAGGCCCTATTGACTGGTCAAGAGAGCCTAGCGGCCCTCGGGTGCCGGTTCTACCGGAATTATGAGGGCTAGCTTTGGAGTTTAGGTGTATTAAACAGAAGTACCGGGTCCGAGAAAGAGGGCGGAGCGTCTATGATAGTCGCCGGGGATGATGCGGCGCCCCACAATAGACACCAACACAACGATGAGGGTCGTCCTTTTGGTCCAACGTTGTTGGTAGTAGTTGACCTTCTTGCAGGGCAGTATAGTGTCATAAGCGCATAGTAATTGGTGCGTATTATGAGCGGCTCTTAATATTATAGCGGCCGTCACGGAATGCTTAGAGGATGAATGGCGCATTCTACCTCGGGATTCAGAACTCGCGTACGCCGGCCGGACAACAGAAGTTAGGGCGCATTACTAGACGTGCTGGACGCCATAGTTATATCGACTTGAGTACGTGCACTCAGGCTGACTTGTTGGCAAAATGACCCTTCAGCATATATCCGTGTAGACTCAACACAGTTGGATTGCGAGAGAGATAGACGTAGAACGCGGACTTCAGCGACGGTAACGCCTCAAGACTCCTGAACAACTTGTACACGAATTTTACCCCATTCCAGAGAAAGGCGATGGGAGATGGTGTAGGGGACTCCAGGACAGCTGGGCTTGCAAGTCTGTCGCCTATATTATAGCATTGTTCCCTTATGCGAGCGGTTCCCTTTACTCCTACAGTAGTACACGAGTTCTTGTGACGGGTCAAACTATCTCGCGTTTCAATGGGGTATGGGTGCCCTAGAACAAATGTAATC'
    
print(DNA2RNA(data))
